/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVoicesRouteImport } from './routes/app.voices'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRecordingsRouteImport } from './routes/app.recordings'
import { Route as AppLibraryRouteImport } from './routes/app.library'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppSettingsTabRouteImport } from './routes/app.settings.$tab'

const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVoicesRoute = AppVoicesRouteImport.update({
  id: '/voices',
  path: '/voices',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordingsRoute = AppRecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsTabRoute = AppSettingsTabRouteImport.update({
  id: '/$tab',
  path: '/$tab',
  getParentRoute: () => AppSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/logs': typeof LogsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/library': typeof AppLibraryRoute
  '/app/recordings': typeof AppRecordingsRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/voices': typeof AppVoicesRoute
  '/app/': typeof AppIndexRoute
  '/app/settings/$tab': typeof AppSettingsTabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/library': typeof AppLibraryRoute
  '/app/recordings': typeof AppRecordingsRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/voices': typeof AppVoicesRoute
  '/app': typeof AppIndexRoute
  '/app/settings/$tab': typeof AppSettingsTabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/logs': typeof LogsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/library': typeof AppLibraryRoute
  '/app/recordings': typeof AppRecordingsRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/voices': typeof AppVoicesRoute
  '/app/': typeof AppIndexRoute
  '/app/settings/$tab': typeof AppSettingsTabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/logs'
    | '/app/history'
    | '/app/library'
    | '/app/recordings'
    | '/app/settings'
    | '/app/voices'
    | '/app/'
    | '/app/settings/$tab'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logs'
    | '/app/history'
    | '/app/library'
    | '/app/recordings'
    | '/app/settings'
    | '/app/voices'
    | '/app'
    | '/app/settings/$tab'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/logs'
    | '/app/history'
    | '/app/library'
    | '/app/recordings'
    | '/app/settings'
    | '/app/voices'
    | '/app/'
    | '/app/settings/$tab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LogsRoute: typeof LogsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/voices': {
      id: '/app/voices'
      path: '/voices'
      fullPath: '/app/voices'
      preLoaderRoute: typeof AppVoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recordings': {
      id: '/app/recordings'
      path: '/recordings'
      fullPath: '/app/recordings'
      preLoaderRoute: typeof AppRecordingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library': {
      id: '/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/$tab': {
      id: '/app/settings/$tab'
      path: '/$tab'
      fullPath: '/app/settings/$tab'
      preLoaderRoute: typeof AppSettingsTabRouteImport
      parentRoute: typeof AppSettingsRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsTabRoute: typeof AppSettingsTabRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsTabRoute: AppSettingsTabRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppHistoryRoute: typeof AppHistoryRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppRecordingsRoute: typeof AppRecordingsRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppVoicesRoute: typeof AppVoicesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHistoryRoute: AppHistoryRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppRecordingsRoute: AppRecordingsRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppVoicesRoute: AppVoicesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LogsRoute: LogsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
