#!/bin/bash
# Install the Vox server LaunchAgent.
# Run once after setup.sh. Re-run after updating Vox.
#
# After install, control the server with:
#   launchctl start  com.melolabdev.vox
#   launchctl stop   com.melolabdev.vox
#   launchctl kickstart -k gui/$(id -u)/com.melolabdev.vox
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
APP_SUPPORT="$HOME/Library/Application Support/Vox"
VENV="$APP_SUPPORT/venv"
PLIST_SRC="$ROOT/launchagent/com.melolabdev.vox.plist"
AGENTS_DIR="$HOME/Library/LaunchAgents"
PLIST_DST="$AGENTS_DIR/com.melolabdev.vox.plist"
LOG_DIR="$HOME/Library/Logs/Vox"
LABEL="com.melolabdev.vox"
SERVER_BUNDLE="$APP_SUPPORT/VoxServer.app"
SIGN_IDENTITY="Developer ID Application: Noelmo Melo (S65X5KY399)"
PREBUILT_ZIP="$ROOT/assets/VoxServer.app.zip"

echo "[vox] Installing server LaunchAgent…"

# Verify setup.sh was run first
if [[ ! -f "$VENV/bin/python" ]]; then
    echo "[vox] ✗ Virtual environment not found at $VENV"
    echo "      Run 'bash setup.sh' first."
    exit 1
fi

# 1. Ensure all required directories exist
mkdir -p "$AGENTS_DIR"
mkdir -p "$LOG_DIR"
mkdir -p "$APP_SUPPORT/api"
mkdir -p "$APP_SUPPORT/scripts"
mkdir -p "$APP_SUPPORT/voices"
mkdir -p "$APP_SUPPORT/outputs"
mkdir -p "$APP_SUPPORT/data"
mkdir -p "$APP_SUPPORT/input/processed"

# 2. Sync server code to permanent location
echo "[vox] Syncing server code to Application Support…"
rsync -a --delete "$ROOT/api/" "$APP_SUPPORT/api/"

# 3. Write the production run.sh into Application Support
cat > "$APP_SUPPORT/scripts/run.sh" <<'RUNSCRIPT'
#!/bin/bash
# Production server start script — managed by launchd.
# Regenerated by install-agent.sh — do not edit directly.
set -e

APP_SUPPORT="$(cd "$(dirname "$0")/.." && pwd)"
VENV="$APP_SUPPORT/venv"

if [[ -f "$APP_SUPPORT/.env" ]]; then
    set -o allexport
    source "$APP_SUPPORT/.env"
    set +o allexport
fi

HOST="${VOX_HOST:-0.0.0.0}"
PORT="${VOX_PORT:-8000}"

cd "$APP_SUPPORT"
exec "$VENV/bin/uvicorn" api.main:app --host "$HOST" --port "$PORT"
RUNSCRIPT
chmod +x "$APP_SUPPORT/scripts/run.sh"
echo "[vox] Production run.sh written to $APP_SUPPORT/scripts/run.sh"

# 4. Build or install VoxServer.app in Application Support
if [[ -f "$PREBUILT_ZIP" ]]; then
    # Use pre-signed bundle from assets/
    echo "[vox] Installing pre-signed VoxServer.app from assets/…"
    rm -rf "$SERVER_BUNDLE"
    ditto -x -k "$PREBUILT_ZIP" "$APP_SUPPORT/"
    echo "[vox] ✓ VoxServer.app installed from pre-signed zip"
else
    # Compile Swift launcher at install time (dev machine only)
    echo "[vox] No pre-signed zip found — compiling VoxServer.app with swiftc…"
    mkdir -p "$SERVER_BUNDLE/Contents/MacOS"
    mkdir -p "$SERVER_BUNDLE/Contents/Resources"

    cat > "$SERVER_BUNDLE/Contents/Info.plist" <<INFOPLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleIdentifier</key>
  <string>com.melolabdev.vox-server</string>
  <key>CFBundleName</key>
  <string>Vox Server</string>
  <key>CFBundleDisplayName</key>
  <string>Vox Server</string>
  <key>CFBundleVersion</key>
  <string>1</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <key>LSUIElement</key>
  <true/>
  <key>LSBackgroundOnly</key>
  <true/>
</dict>
</plist>
INFOPLIST

    LAUNCHER_SRC="$(mktemp /tmp/vox-server-launcher-XXXXXX.swift)"
    cat > "$LAUNCHER_SRC" <<SWIFT
import Foundation

let home = FileManager.default.homeDirectoryForCurrentUser.path
let script = "\(home)/Library/Application Support/Vox/scripts/run.sh"

let process = Process()
process.executableURL = URL(fileURLWithPath: "/bin/bash")
process.arguments = [script]
try? process.run()
process.waitUntilExit()
SWIFT

    echo "[vox] Compiling launcher binary…"
    swiftc -O -o "$SERVER_BUNDLE/Contents/MacOS/vox-server" "$LAUNCHER_SRC"
    rm -f "$LAUNCHER_SRC"

    # Sign if cert is available
    if security find-identity -v -p codesigning 2>/dev/null | grep -qF "$SIGN_IDENTITY"; then
        echo "[vox] Signing VoxServer.app…"
        codesign --deep --force --options runtime \
            --sign "$SIGN_IDENTITY" \
            "$SERVER_BUNDLE"
        echo "[vox] ✓ Signed with $SIGN_IDENTITY"
    else
        echo "[vox] ⚠ Signing identity not found — skipping codesign"
    fi

    echo "[vox] VoxServer.app built at: $SERVER_BUNDLE"
fi

# 5. Write the final plist — server now runs entirely from APP_SUPPORT
sed \
  -e "s|VOX_APP_SUPPORT|$APP_SUPPORT|g" \
  -e "s|VOX_LOG_DIR|$LOG_DIR|g" \
  "$PLIST_SRC" > "$PLIST_DST"

echo "[vox] Plist written to: $PLIST_DST"

# 6. Unload any previously loaded version
launchctl unload "$PLIST_DST" 2>/dev/null || true

# 7. Load the agent
launchctl load "$PLIST_DST"

echo ""
echo "[vox] Server LaunchAgent installed."
echo ""
echo "  Start:   launchctl start  $LABEL"
echo "  Stop:    launchctl stop   $LABEL"
echo "  Restart: launchctl kickstart -k gui/\$(id -u)/$LABEL"
echo "  Logs:    tail -f $LOG_DIR/vox.log"
echo "  Errors:  tail -f $LOG_DIR/vox-error.log"
echo ""
echo "  NOTE: The server does NOT start automatically on login."
echo "  Start it from the Vox Helper menu bar icon."
