#!/bin/bash
# Install the VoxForge server LaunchAgent.
# Run once after setup.sh. Re-run after updating Vox.
#
# After install, control the server with:
#   launchctl start  com.melolabdev.vox
#   launchctl stop   com.melolabdev.vox
#   launchctl kickstart -k gui/$(id -u)/com.melolabdev.vox
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
APP_SUPPORT="$HOME/Library/Application Support/VoxForge"
VENV="$APP_SUPPORT/venv"
PLIST_SRC="$ROOT/launchagent/com.melolabdev.vox.plist"
AGENTS_DIR="$HOME/Library/LaunchAgents"
PLIST_DST="$AGENTS_DIR/com.melolabdev.vox.plist"
LOG_DIR="$HOME/Library/Logs/VoxForge"
LABEL="com.melolabdev.vox"

echo "[vox] Installing server LaunchAgent…"

# Verify setup.sh was run first
if [[ ! -f "$VENV/bin/python" ]]; then
    echo "[vox] ✗ Virtual environment not found at $VENV"
    echo "      Run 'bash setup.sh' first."
    exit 1
fi

# 1. Ensure all required directories exist
mkdir -p "$AGENTS_DIR"
mkdir -p "$LOG_DIR"
mkdir -p "$APP_SUPPORT/api"
mkdir -p "$APP_SUPPORT/config/presets"
mkdir -p "$APP_SUPPORT/scripts"
mkdir -p "$APP_SUPPORT/voices"
mkdir -p "$APP_SUPPORT/outputs"
mkdir -p "$APP_SUPPORT/data"
mkdir -p "$APP_SUPPORT/input/processed"

# 2. Sync server code to permanent location
echo "[vox] Syncing server code to Application Support…"
rsync -a --delete "$ROOT/api/"    "$APP_SUPPORT/api/"
rsync -a --delete "$ROOT/config/" "$APP_SUPPORT/config/"

# 3. Write the production run.sh into Application Support
# This script is self-contained — references APP_SUPPORT by its own location.
cat > "$APP_SUPPORT/scripts/run.sh" <<'RUNSCRIPT'
#!/bin/bash
# Production server start script — managed by launchd.
# Regenerated by install-agent.sh — do not edit directly.
set -e

APP_SUPPORT="$(cd "$(dirname "$0")/.." && pwd)"
VENV="$APP_SUPPORT/venv"

if [[ -f "$APP_SUPPORT/.env" ]]; then
    set -o allexport
    source "$APP_SUPPORT/.env"
    set +o allexport
fi

HOST="${VOX_HOST:-0.0.0.0}"
PORT="${VOX_PORT:-8000}"

cd "$APP_SUPPORT"
exec "$VENV/bin/uvicorn" api.main:app --host "$HOST" --port "$PORT"
RUNSCRIPT
chmod +x "$APP_SUPPORT/scripts/run.sh"
echo "[vox] Production run.sh written to $APP_SUPPORT/scripts/run.sh"

# 4. Write the final plist — server now runs entirely from APP_SUPPORT
sed \
  -e "s|VOX_APP_SUPPORT|$APP_SUPPORT|g" \
  -e "s|VOX_LOG_DIR|$LOG_DIR|g" \
  "$PLIST_SRC" > "$PLIST_DST"

echo "[vox] Plist written to: $PLIST_DST"

# 5. Unload any previously loaded version
launchctl unload "$PLIST_DST" 2>/dev/null || true

# 6. Load the agent
launchctl load "$PLIST_DST"

echo ""
echo "[vox] Server LaunchAgent installed."
echo ""
echo "  Start:   launchctl start  $LABEL"
echo "  Stop:    launchctl stop   $LABEL"
echo "  Restart: launchctl kickstart -k gui/\$(id -u)/$LABEL"
echo "  Logs:    tail -f $LOG_DIR/vox.log"
echo "  Errors:  tail -f $LOG_DIR/vox-error.log"
echo ""
echo "  NOTE: The server does NOT start automatically on login."
echo "  When shipping the .app, set RunAtLoad=true in the plist"
echo "  and re-run this script. See BACKLOG.md for details."
