PRESETS: dict[str, dict] = {
    "confident": {
        "temperature": 0.7,
        "exaggeration": 0.5,
        "cfg_weight": 0.65,
        "repetition_penalty": 1.2,
        "top_p": 0.9,
        "min_p": 0.05,
    },
    "calm": {
        "temperature": 0.5,
        "exaggeration": 0.2,
        "cfg_weight": 0.6,
        "repetition_penalty": 1.1,
        "top_p": 0.85,
        "min_p": 0.05,
    },
    "soft-spoken": {
        "temperature": 0.45,
        "exaggeration": 0.15,
        "cfg_weight": 0.65,
        "repetition_penalty": 1.1,
        "top_p": 0.8,
        "min_p": 0.05,
    },
    "polite": {
        "temperature": 0.6,
        "exaggeration": 0.3,
        "cfg_weight": 0.6,
        "repetition_penalty": 1.15,
        "top_p": 0.88,
        "min_p": 0.05,
    },
    "enthusiastic": {
        "temperature": 0.85,
        "exaggeration": 0.75,
        "cfg_weight": 0.55,
        "repetition_penalty": 1.25,
        "top_p": 0.95,
        "min_p": 0.05,
    },
    "dramatic": {
        "temperature": 0.9,
        "exaggeration": 0.95,
        "cfg_weight": 0.5,
        "repetition_penalty": 1.3,
        "top_p": 0.95,
        "min_p": 0.04,
    },
    "angry": {
        "temperature": 0.95,
        "exaggeration": 0.9,
        "cfg_weight": 0.45,
        "repetition_penalty": 1.35,
        "top_p": 0.98,
        "min_p": 0.03,
    },
    "sarcastic": {
        "temperature": 0.85,
        "exaggeration": 0.8,
        "cfg_weight": 0.5,
        "repetition_penalty": 1.3,
        "top_p": 0.95,
        "min_p": 0.04,
    },
    "newsreader": {
        "temperature": 0.4,
        "exaggeration": 0.2,
        "cfg_weight": 0.72,
        "repetition_penalty": 1.1,
        "top_p": 0.8,
        "min_p": 0.05,
    },
    "storyteller": {
        "temperature": 0.78,
        "exaggeration": 0.65,
        "cfg_weight": 0.55,
        "repetition_penalty": 1.2,
        "top_p": 0.92,
        "min_p": 0.05,
    },
    # Legacy alias — kept for backwards compatibility with saved jobs/presets
    "default": {
        "temperature": 0.7,
        "exaggeration": 0.5,
        "cfg_weight": 0.65,
        "repetition_penalty": 1.2,
        "top_p": 0.9,
        "min_p": 0.05,
    },
}
